name: Build Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '构建分支'
        required: false
        type: string
        default: ''
      modules:
        description: '构建模块 (默认: server)'
        required: false
        type: string
        default: 'server'

jobs:
  build-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: 释放磁盘空间
        run: |
          echo "清理前的磁盘空间："
          df -h
          
          # 删除不需要的软件和文件
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
          # 删除Docker镜像
          docker rmi $(docker images -q) || true
          
          # 清理apt缓存
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          
          # 删除大型软件包
          sudo apt-get remove -y '^aspnetcore-.*' || true
          sudo apt-get remove -y '^dotnet-.*' --fix-missing || true
          sudo apt-get remove -y '^llvm-.*' --fix-missing || true
          sudo apt-get remove -y 'php.*' --fix-missing || true
          sudo apt-get remove -y '^mongodb-.*' --fix-missing || true
          sudo apt-get remove -y '^mysql-.*' --fix-missing || true
          sudo apt-get remove -y azure-cli google-chrome-stable firefox || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          echo "清理后的磁盘空间："
          df -h
      
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3 \
            python3-pip \
            libglu1-mesa-dev \
            libgl1-mesa-dev \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-xkb1 \
            libxkbcommon-dev \
            p7zip-full \
            curl \
            wget
      
      - name: 安装 Python 依赖
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
      
      - name: 清理npm冲突文件
        run: |
          sudo rm -f /usr/local/bin/grunt
          sudo rm -f /usr/local/bin/pkg
        continue-on-error: true
      
      - name: 执行构建
        run: |
          echo "构建前磁盘空间："
          df -h
          
          python3 --version
          cd tools/linux
          pwd
          ls
          if [ -n "${{ inputs.branch }}" ]; then
            echo ${{ inputs.modules }} ${{ inputs.branch }}
            python3 ./automate.py ${{ inputs.modules }} --branch=${{ inputs.branch }}
          else
            echo ${{ inputs.modules }}
            python3 ./automate.py ${{ inputs.modules }}
          fi
          
          echo "构建后磁盘空间："
          df -h
      
      - name: 清理构建临时文件
        run: |
          echo "清理前磁盘空间："
          df -h
          
          # 清理Qt源码（保留编译好的qt_build）
          cd tools/linux
          sudo rm -rf qt-everywhere-opensource-src-* || true
          sudo rm -rf *.tar.xz || true
          sudo rm -rf *.7z || true
          
          # 清理npm缓存
          sudo rm -rf /root/.npm || true
          sudo rm -rf ~/.npm || true
          
          # 清理其他构建缓存
          sudo rm -rf /tmp/* || true
          
          echo "清理后磁盘空间："
          df -h
      
      - name: 查找构建产物
        id: find_artifacts
        run: |
          echo "查找构建产物..."
          if [ -d "out" ]; then
            echo "找到 out 目录"
            ls -lah out/
            echo "artifact_path=out" >> $GITHUB_OUTPUT
          elif [ -d "tools/linux/out" ]; then
            echo "找到 tools/linux/out 目录"
            ls -lah tools/linux/out/
            echo "artifact_path=tools/linux/out" >> $GITHUB_OUTPUT
          elif [ -d "server" ]; then
            echo "找到 server 目录"
            ls -lah server/
            echo "artifact_path=server" >> $GITHUB_OUTPUT
          else
            echo "在根目录查找所有可能的产物目录..."
            find . -maxdepth 3 -type d \( -name "out" -o -name "build" -o -name "dist" -o -name "*server*" \) -exec ls -lah {} \;
            echo "artifact_path=." >> $GITHUB_OUTPUT
          fi
      
      - name: 打包构建产物
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          ARTIFACT_NAME="onlyoffice-server-build-${TIMESTAMP}"
          
          if [ -d "out" ]; then
            tar -czf ${ARTIFACT_NAME}.tar.gz -C out .
          elif [ -d "tools/linux/out" ]; then
            tar -czf ${ARTIFACT_NAME}.tar.gz -C tools/linux/out .
          elif [ -d "server" ]; then
            tar -czf ${ARTIFACT_NAME}.tar.gz -C server .
          else
            echo "未找到标准构建目录，打包整个workspace（排除源代码）"
            tar -czf ${ARTIFACT_NAME}.tar.gz \
              --exclude='.git' \
              --exclude='node_modules' \
              --exclude='qt_build' \
              --exclude='qt-everywhere-opensource-src-*' \
              --exclude='*.tar.xz' \
              --exclude='*.7z' \
              .
          fi
          
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.tar.gz
          retention-days: 30
      
      - name: 构建摘要
        run: |
          echo "## 构建完成 ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 构建信息" >> $GITHUB_STEP_SUMMARY
          echo "- **构建模块**: ${{ inputs.modules }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ inputs.branch }}" ]; then
            echo "- **构建分支**: ${{ inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **构建分支**: 当前分支" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **构建时间**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 下载产物" >> $GITHUB_STEP_SUMMARY
          echo "构建产物已打包为: \`${ARTIFACT_NAME}.tar.gz\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "请在 Actions 页面的 Artifacts 部分下载构建产物。" >> $GITHUB_STEP_SUMMARY

